# Generated by Django 3.2 on 2021-04-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trigram_index',
            field=models.CharField(blank=True, max_length=522, null=True),
        ),
    ]
